### ISSUE TITLE
Use different feed?

### ISSUE THREAD

**Issue by grischard** [iicky/homeassistant-mta-subway#3]
https://collector-otp-prod.camsys-apps.com/realtime/gtfsrt/ALL/alerts?type=json seems to be the feed that the MTA website uses.

**Comment by grischard** [comment]
I've asked @blahblahblah- on Twitter if it'd be ok to use https://www.goodservice.io/api/routes

https://twitter.com/grischard/status/1512170937113882633

**Comment by Madelena** [comment]
This is amazing! While we are at it, it would be nice to integrate the [Service Change notices](https://www.goodservice.io/trains/L) (i.e. why the train is delayed) as an attribute. I wonder if @blahblahblah- has an API for that?

Edit: API is https://www.goodservice.io/api/routes/{route-id}, e.g. https://www.goodservice.io/api/routes/L

**Comment by sunny-ng** [comment]
There's also this one that has everything: https://www.goodservice.io/api/routes?detailed=1

**Comment by DaAwesomeP** [comment]
Why not these? https://api.mta.info/#/landing

**Comment by iicky** [comment]
> There's also this one that has everything: https://www.goodservice.io/api/routes?detailed=1

This looks fantastic! Will start working on implementing it.

**Comment by iicky** [comment]
I changed over to the [goodservice.io](https://www.goodservice.io/api/routes?detailed=1) detailed feed - let me know how it works.
